### ISSUE TITLE
May I ask where is the specific download link for the first NIH data set in the next paper? Is it a public data set or a private data set NIH dataset:  The abdominal medical images of CT and MRI were collected from 393 patients at the NIH Clinical Center from January 2019  to October 2021

### ISSUE THREAD

**Issue by computerAItest** [boahK/OTMorph#1]
May I ask where is the specific download link for the first NIH data set in the next paper? Is it a public data set or a private data set
NIH dataset:  The abdominal medical images of CT and MRI were collected from 393 patients at the NIH Clinical Center from January 2019  to October 2021

**Comment by boahK** [comment]
Hi. 
The NIH dataset is a private data set. Thanks for your interest in our paper though.
